# Generated by Django 5.0.2 on 2024-02-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=15)),
                ('platform_user', models.CharField(max_length=15)),
            ],
        ),
    ]
