# Generated by Django 5.0.2 on 2024-02-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='user_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
