# Generated by Django 5.0.2 on 2024-02-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social',
        ),
    ]
