# Generated by Django 5.0.2 on 2024-02-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_social_id_alter_social_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='social',
            name='id',
        ),
        migrations.AddField(
            model_name='social',
            name='id',
            field=models.ManyToManyField(blank=True, to='ecommerce.user'),
        ),
    ]
