# Generated by Django 5.0.2 on 2024-02-19 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_order_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=15)),
                ('summary', models.CharField(max_length=100)),
                ('price', models.FloatField(blank=True, null=True)),
                ('discount_type', models.CharField(max_length=15)),
                ('discount_value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.category')),
            ],
        ),
    ]
