# Generated by Django 5.0.2 on 2024-02-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='platform',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='platform_user',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
